---

include:
  - '/.gitlab/ci/stages/globals.yml'
  - '/.gitlab/ci/stages/build_and_push.yml'
  - project: 'CorSAIR/ci-cd/pipeline-templates'
    # yamllint disable-line rule:line-length
    ref: RND-793_ExtractDynamicallyIncludablePipelineConfigurationFilesIntoStandaloneRepository
    file: '/.gitlab/ci/stages/pull.yml'
  - project: 'CorSAIR/ci-cd/pipeline-templates'
    # yamllint disable-line rule:line-length
    ref: RND-793_ExtractDynamicallyIncludablePipelineConfigurationFilesIntoStandaloneRepository
    file: '/.gitlab/ci/stages/sast.yml'
  - project: 'CorSAIR/ci-cd/pipeline-templates'
    # yamllint disable-line rule:line-length
    ref: RND-793_ExtractDynamicallyIncludablePipelineConfigurationFilesIntoStandaloneRepository
    file: '/.gitlab/ci/stages/code_quality.yml'

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - .cache/pypoetry
    - .venv

stages:
  - Build & Push
  - Pull Docker Image
  - SAST
  - Code Quality
