---

include:
  - project: 'CorSAIR/ci-cd/pipeline-templates'
    ref: master
    file:
      - '/.gitlab/ci/stages/globals.yml'
      # yamllint disable-line rule:line-length
      - '/.gitlab/ci/stages/build_and_push_docker_image/jobs/dockerfiles-dir-filename-namespaced-images.yml'
      - '/.gitlab/ci/stages/pull_docker_image/jobs/pull.yml'
      - '/.gitlab/ci/stages/sast/jobs/all.yml'
      - '/.gitlab/ci/stages/code_quality/jobs/pre-commit-hooks.yml'

stages:
  - Build & Push Docker Image
  - Pull Docker Image
  - SAST
  - Code Quality

variables:
  CI_REGISTRY_IMAGE: "${DOCKER_NAMESPACE}/${CI_PROJECT_NAME}"
  # yamllint disable-line rule:line-length
  CI_DOCKERFILE_FILENAME: "pyenv-python-3.7.9-3.8.6-3.9.4-poetry-hadolint-go-1.16.3"
  # yamllint disable-line rule:line-length
  CI_IMAGE: "${DOCKER_NAMESPACE}/${CI_PROJECT_NAME}:${CI_DOCKERFILE_FILENAME}_${CI_COMMIT_SHORT_SHA}"
  TAG_SUFFIX: "_${CI_COMMIT_SHORT_SHA}"
  REPLICA_TAG_SUFFIX: "_${CI_COMMIT_REF_SLUG}"
