---

include:
  - '/.gitlab/ci/stages/globals.yml'
  - '/.gitlab/ci/stages/build_and_push.yml'
  - '/.gitlab/ci/stages/pull.yml'
  - '/.gitlab/ci/stages/sast.yml'
  - '/.gitlab/ci/stages/code_quality.yml'

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - .cache/pypoetry
    - .venv

stages:
  - Build & Push
  - pull
  - SAST
  - Code Quality
