---

include:
  - project: 'CorSAIR/ci-cd/pipeline-templates'
    # yamllint disable-line rule:line-length
    ref: RND-793_ExtractDynamicallyIncludablePipelineConfigurationFilesIntoStandaloneRepository
    file: '/.gitlab/ci/stages/globals.yml'
  - project: 'CorSAIR/ci-cd/pipeline-templates'
    # yamllint disable-line rule:line-length
    ref: RND-793_ExtractDynamicallyIncludablePipelineConfigurationFilesIntoStandaloneRepository
    file: '/.gitlab/ci/stages/build_and_push_docker_image/jobs/multi.yml'
  - project: 'CorSAIR/ci-cd/pipeline-templates'
    # yamllint disable-line rule:line-length
    ref: RND-793_ExtractDynamicallyIncludablePipelineConfigurationFilesIntoStandaloneRepository
    file: '/.gitlab/ci/stages/pull_docker_image.yml'
  - project: 'CorSAIR/ci-cd/pipeline-templates'
    # yamllint disable-line rule:line-length
    ref: RND-793_ExtractDynamicallyIncludablePipelineConfigurationFilesIntoStandaloneRepository
    file: '/.gitlab/ci/stages/sast/jobs/scan-dependencies.yml'
  - project: 'CorSAIR/ci-cd/pipeline-templates'
    # yamllint disable-line rule:line-length
    ref: RND-793_ExtractDynamicallyIncludablePipelineConfigurationFilesIntoStandaloneRepository
    file: '/.gitlab/ci/stages/sast/jobs/scan-container.yml'
  - project: 'CorSAIR/ci-cd/pipeline-templates'
    # yamllint disable-line rule:line-length
    ref: RND-793_ExtractDynamicallyIncludablePipelineConfigurationFilesIntoStandaloneRepository
    file: '/.gitlab/ci/stages/code_quality.yml'

stages:
  - Build & Push Docker Image
  - Pull Docker Image
  - SAST
  - Code Quality

variables:
  CI_REGISTRY_IMAGE: "${DOCKER_NAMESPACE}/${CI_PROJECT_NAME}"
  # yamllint disable-line rule:line-length
  CI_DOCKERFILE_FILENAME: "pyenv-python-3.7.9-3.8.6-3.9.0-poetry-hadolint-go-1.15.5"
  # yamllint disable-line rule:line-length
  CI_IMAGE: "${DOCKER_NAMESPACE}/${CI_PROJECT_NAME}:${CI_DOCKERFILE_FILENAME}_${CI_COMMIT_SHORT_SHA}"
  TAG_SUFFIX: "_${CI_COMMIT_SHORT_SHA}"
  REPLICA_TAG_SUFFIX: "_${CI_COMMIT_REF_SLUG}"
