---
repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
      - id: detect-secrets
        exclude: poetry.lock

  - repo: local
    hooks:
      - id: hadolint
        name: hadolint
        description: Runs hadolint to lint Dockerfiles
        language: system
        entry: hadolint
        types: [dockerfile]

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: script-must-have-extension
      - id: script-must-not-have-extension

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.1
    hooks:
      - id: yamllint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files  # Ignored for git-lfs files
        args: [--maxkb=100000]  # 100MB
      - id: end-of-file-fixer  # Ensure files ONLY end in a newline
      - id: trailing-whitespace  # Trim
        args: [--markdown-linebreak-ext=md]
